restructure and make default graviton

diff --git a/bin/instance_state b/bin/instance_state
--- a/bin/instance_state
+++ b/bin/instance_state
@@ -1,4 +1,14 @@
 #!/usr/bin/env bash
+# shellcheck disable=1091
+
+source colours 2>/dev/null
+
+CWD=$(basename "$(pwd)")
+if [ "$CWD" == "bin" ]; then
+    echo "${RED}Error: Script cannot be executed directly from inside ${CWD}.${NORM}"
+    exit 1
+fi
+
 id=$(terraform output -raw instance_id)
 name=$(terraform output -raw instance_name)
 echo "Getting instance state for ez_tf_ec2_instance:
